### PR TITLE
doc: refer specific verision of Tekton not latest

### PR DESCRIPTION
**Pull request by matejvasek**

### CODE REVIEW

**Comment by jrangelramos** [comment]
Hi @matejvasek I think we could also change here https://github.com/knative/func/blob/main/hack/tekton.sh#L25 to match the suggested version on this PR.

**Comment by matejvasek** [comment]
@zroubalik PTAL

**Comment by matejvasek** [comment]
> Hi @matejvasek I think we could also change here https://github.com/knative/func/blob/main/hack/tekton.sh#L25 to match the suggested version on this PR.

@jrangelramos fixed.

**Comment by matejvasek** [comment]
@zroubalik please override the check.

**Comment by kvmware** [comment]
https://github.com/knative/actions/pull/132 should fix that check fail

**Pull request merged**
