### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by matejvasek**

### CODE REVIEW

**Review by upodroid — APPROVED** [review]
LGTM

**Comment by gauron99** [comment]
wouldnt it be better like `func delete with explicit name as argument` or `func delete explicitly with name as argument` ? not sure if my english is correct here :D

**Comment by matejvasek** [comment]
@gauron99 plz lgtm

**Comment by gauron99** [comment]
LGTM

**Review by gauron99 — APPROVED** [review]

**Pull request merged**
