### PR TITLE
Adding GO s2i to e2e test suite

### PR DESCRIPTION
**Pull request by jrangelramos**
# Changes

- Add e2e tests for Go functions using s2i builder (**except** for OnCluster builds scenarios)

### CODE REVIEW

**Comment by matejvasek** [comment]
@lkingland I think these test failures might be caused by actual bug.

**Comment by matejvasek** [comment]
It appears that on cluster build is still broken.
Maybe enable only local build tests for now?

**Comment by jrangelramos** [comment]
yea.. it is failling oncluster build for Go S2i. I would prefer to keep this test until this get sorted out as well.

**Comment by jrangelramos** [comment]
Apparently the same work for scaffold the go s2i func is required to be done during the oncluster build (perhaps in some task in between the tekton git-source/push and build tasks). I'm just leaving the oncluster test coverage apart and will add it later when oncluster build approach for go is sorted out

**Comment by jrangelramos** [comment]
Hi @matejvasek coud you please re-LTGM

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
