### PR TITLE
func invoke handles json properly

### LINKED ISSUE #2241: Func invoke encodes json data differently than curl
When sending events with json data with `func invoke`, the way in which the data is encoded in the event behaves differently than when using curl to call the function, which is confusing.

To reproduce:

1. Clone https://github.com/Cali0707/func-invoke-confusion
2. Run the function with `func run`
3. Send an event to the function with curl:
```bash
curl -X POST http://localhost:8080/ \
 -H "ce-id: 12345" \
 -H "ce-source: curl" \
 -H "ce-type: this.will.work" \
 -H "ce-specversion: 1.0" \
 -H "Content-Type: application/json" \
 -d '{"customerId": "0123456", "productId": "6543210"}'
```
4. Send an event to the function with `func invoke`:
```bash
func invoke --data '{"customerId": "0123456", "productId": "6543210"}'
```
5. Check the logs from the function, they will look like:
```
listening on http port 8080
Running on host port 8080
Received event
Context Attributes,
  specversion: 1.0
  type: this.will.work
  source: curl
  id: 12345
  datacontenttype: application/json
Data,
  {
    "customerId": "0123456",
    "productId": "6543210"
  }

Successfully decoded purchase: &{CustomerId:0123456 ProductId:6543210}Received event
Context Attributes,
  specversion: 1.0
  type: boson.fn
  source: /boson/fn
  id: 0385ddeb-043a-472d-93a9-e7b281ba319a
  time: 2024-03-20T20:53:50.985375048Z
  datacontenttype: application/json
Data,
  "{\"customerId\": \"0123456\", \"productId\": \"6543210\"}"

Failed to decode event:  [json] found bytes ""{\"customerId\": \"0123456\", \"productId\": \"6543210\"}"", but failed to unmarshal: json: cannot unmarshal string into Go value of type function.Purchase
```

I'm not sure if this is the expected behaviour or not, but if it is it might be worth mentioning this somewhere, as I expected that it would behave the same way as curl and send json, rather than a json encoded string.

### PR DESCRIPTION
**Pull request by Cali0707**
# Changes

- :bug: func invoke sets the data in the event after unmarshalling the string, so that the event does not treat the data as a json string
-
-

/kind bug

Fixes #2241 

**Release Note**

```release-note
func invoke now correctly handles data with contenttype application/json
```

### CODE REVIEW

**Comment by Cali0707** [comment]
/cc @lkingland @matejvasek 

Let me know if you think it would be better to make this work more generically for other contenttypes/if you have an idea how to do that. For now, this fix is specific to application/json

**Comment by Leo6Leo** [comment]
I can testify that the fix works on my end.

**Review by lkingland — APPROVED** [review]
Thank you for the contribution @Cali0707

/lgtm
/approve

**Comment by pierDipi** [comment]
@lkingland @Cali0707 should this be backported for a patch release?

**Comment by lkingland** [comment]
> @lkingland @Cali0707 should this be backported for a patch release?

Thanks for asking.

This is a feature/enhancement, so I see no need to backport.

**Pull request merged**
