### PR TITLE
adding `--path` option to `subscribe` command

### PR DESCRIPTION
**Pull request by jrangelramos**
# Changes

- :gift: Added `--path` option to `func subscribe` command in order to align with other commands

/kind enhancement

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

thanks for this! I was clearly not aware of this, initially! Greatly appreciated!

**Comment by matejvasek** [comment]
@ReToCode would you please override the "Integration Test (ubuntu-latest)" failure?

**Pull request merged**
