### PR TITLE
src: update func go runtime dep

### PR DESCRIPTION
**Pull request by lkingland**
:broom: updates func runtime dependency

/kind cleanup

### CODE REVIEW

**Comment by lkingland** [comment]
> @lkingland it looks like newer version of runtime is not Windows compatible. [lkingland/func-runtime-go@0fd4ffe](https://github.com/lkingland/func-runtime-go/commit/0fd4ffebaff3081f228ab581ae357f0fc9f46994) -- the signal is not defined on windows.

Thanks! I updated the filter to only apply for linux, and to compare by hex

**Comment by matejvasek** [comment]
@lkingland  The `TestBuilder_Concurrency` test is failing too often at Windows, isn't there really a bug?

**Comment by matejvasek** [comment]
@lkingland I believe there is really a bug on Windows. I can reproduce it.

**Comment by matejvasek** [comment]
a) It looks like "normal" user cannot create symlink:
```
=== RUN   TestBuilder_Concurrency
mkdir -p C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1529383575\001\.func\builds\by-hash\b097429205e010f2b4a96d9a80860c0335bd0d961
f761ead9e3ba79396ace1ce
mkdir -p C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1529383575\001\.func\builds\by-pid
ln -s ..\by-hash\b097429205e010f2b4a96d9a80860c0335bd0d961f761ead9e3ba79396ace1ce C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1529
383575\001\.func\builds\by-pid\8220
test build error symlink ..\by-hash\b097429205e010f2b4a96d9a80860c0335bd0d961f761ead9e3ba79396ace1ce C:\Users\mvasek\AppData\Local\Temp\TestBuil
der_Concurrency1529383575\001\.func\builds\by-pid\8220: A required privilege is not held by the client.panic: test timed out after 10s
```
b) even when running as an admin there is another issue:
```
=== RUN   TestBuilder_Concurrency
mkdir -p C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1347840251\001\.func\builds\by-hash\d9434b8b4ec1e5e485daa9a248a3c59272b36f0c8
cce8b41d58ef305bae69c56
mkdir -p C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1347840251\001\.func\builds\by-pid
ln -s ..\by-hash\d9434b8b4ec1e5e485daa9a248a3c59272b36f0c8cce8b41d58ef305bae69c56 C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1347
840251\001\.func\builds\by-pid\19300
ΓåÆ /func
ΓåÆ /func/README.md
ΓåÆ /func/func.yaml
ΓåÆ /func/go.mod
ΓåÆ /func/handle.go
ΓåÆ /func/handle_test.go
mv .\datalayer.tar.gz .\oci\blobs\sha256\2a2c63a63996284d9070f746d9225c6db3f10040404a318d315410e9990a2e01
ΓåÆ /etc/ssl/certs/ca-certificates.crt
ΓåÆ /etc/pki/tls/certs/ca-certificates.crt
mv .\certslayer.tar.gz .\oci\blobs\sha256\3650df3d1bb6e357be8bca5bdc04df36f9e3b973fb221d9cdce3193ae10a08c7
rm -rf C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1347840251\001\.func\builds\by-hash\d9434b8b4ec1e5e485daa9a248a3c59272b36f0c8cc
e8b41d58ef305bae69c56
test build error remove C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1347840251\001\.func\builds\by-hash\d9434b8b4ec1e5e485daa9a248
a3c59272b36f0c8cce8b41d58ef305bae69c56\config.json: The process cannot access the file because it is being used by another process.mv .\config.j
son .\oci\blobs\sha256\f72f75e96f760d68fafd1c64a01752c66f18c5a6a5791f938927b833750d944e
rm C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1347840251\001\.func\builds\by-pid\19300
rm C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1347840251\001\.func\builds\by-hash\d9434b8b4ec1e5e485daa9a248a3c59272b36f0c8cce8b4
1d58ef305bae69c56
test build error rename C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1347840251\001\.func\builds\by-hash\d9434b8b4ec1e5e485daa9a248
a3c59272b36f0c8cce8b41d58ef305bae69c56\config.json C:\Users\mvasek\AppData\Local\Temp\TestBuilder_Concurrency1347840251\001\.func\builds\by-hash
\d9434b8b4ec1e5e485daa9a248a3c59272b36f0c8cce8b41d58ef305bae69c56\oci\blobs\sha256\f72f75e96f760d68fafd1c64a01752c66f18c5a6a5791f938927b833750d9
44e: The system cannot find the path specified.panic: test timed out after 10s
```

**Comment by matejvasek** [comment]
It's probably not introduced by this PR but still needs fixing.

**Comment by lkingland** [comment]
> @lkingland I believe there is really a bug on Windows. I can reproduce it.

That's great news you can reproduce!

**Pull request merged**
