### PR TITLE
fix: oncluster builds registry mismatch error

### LINKED ISSUE #1541: On Cluster builds (from Git) fails with "different registry than the current configured"
It seems there is a mismatch on the logic behind build process On Cluster and local.
On local build, let's say using the below steps, `func.yaml` get updated with the built image and the registry ...
```
$ func create -l node /tmp/samplefunc
Created node function in /tmp/samplefunc
$ func build -p /tmp/samplefunc -r ttl.sh/jrangelramos-sample
   🙌 Function image built: ttl.sh/jrangelramos-sample/samplefunc:latest
$ awk '/^image:|^registry:/' /tmp/samplefunc/func.yaml 
registry: ttl.sh/jrangelramos-sample
image: ttl.sh/jrangelramos-sample/samplefunc:latest
$ func deploy -p /tmp/samplefunc --build=false
   ✅ Function created in namespace "sample-test" and exposed at URL: 
   https://samplefunc-sample-test.apps.mycluster.net
```

A build on cluster (from git) does not follow the same pattern. Build tasks just update the  `image` field on `func.yaml` and leave the `registry` untouched. This is causing deploy process to fails by stating the registry is different than the current configured.

```
$ func deploy -p /tmp/TestBasicGit521085418/001/test-func-basic-gittj42g -r ttl.sh/knfunccejia9x1 --remote --verbose --git-url http://func-git.build-test.svc.cluster.local/test-func-basic-gittj42g.git
Creating Pipeline resources
Running Pipeline Task: Fetching git repository with the function source code
Running Pipeline Task: Building function image on the cluster
Running Pipeline Task: Deploying function to the cluster
Error: failed to run pipeline: function pipeline run has failed with message: 

Warning: function has current image 'ttl.sh/knfunccejia9x1/test-func-basic-gittj42g:latest' which has a different registry than the currently configured registry 'image-registry.openshift-image-registry.svc:5000/build-test'. The new image tag will be 'image-registry.openshift-image-registry.svc:5000/build-test/test-func-basic-gittj42g:latest'.  To use an explicit image, use --image.
⬆️  Deploying function to the cluster
Waiting for Knative Service to become ready
deploy error: knative deployer failed to wait for the Knative Service to become ready: RevisionFailed: Revision "test-func-basic-gittj42g-00001" failed with message: Unable to fetch image "image-registry.openshift-image-registry.svc:5000/build-test/test-func-basic-gittj42g:latest": failed to resolve image to digest: HEAD https://image-registry.openshift-image-registry.svc:5000/v2/build-test/test-func-basic-gittj42g/manifests/latest: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details).
```

### PR DESCRIPTION
**Pull request by jrangelramos**
# Changes

- :bug: Fix oncluster builds registry error

Fixes #1541

### CODE REVIEW

**Comment by lance** [comment]
@jrangelramos this looks OK to me. Is it still WIP?

**Comment by jrangelramos** [comment]
Hello @lance ! Well,actually the fix is done! But it was as draft since it seems this issue with registry would be discussed on the next work group call (and the workaround I'm suggesting here may not be the ideal one). /cc @lkingland

**Comment by matejvasek** [comment]
I think we can merge this for now.

**Comment by matejvasek** [comment]
We can remove "registry" latter.

**Pull request merged**
