### PR TITLE
feat(templates): remove liveness and readiness from defaults

### PR DESCRIPTION
**Pull request by lance**
# Changes

The liveness and readiness URLs are defined in code as defaulting to `/health/liveness` and `/health/readiness` respectively. The deploy command handles these defaults without requiring them to exist in the `func.yaml` file. Existing tests for defaults and overrides already exist, so this change does not require additional tests to be included.

/kind enhancement

Fixes: https://github.com/knative/func/issues/1281

**Release Note**

```release-note
removes default endpoints from func.yaml to improve file legibility
```

### CODE REVIEW

**Comment by lance** [comment]
/hold
It seems this is a little naive.

**Review by lkingland — APPROVED** [review]
If it passes tests, this is precisely what I was hoping would work!

/lgtm
/hold for zbynek's massive refactor to the repo to land first, which was submitted one hour prior

**Comment by lance** [comment]
@lkingland after rebasing, I need another /lgtm please

**Review by lkingland — APPROVED** [review]

**Review by zroubalik — APPROVED** [review]
/lgtm

**Pull request merged**
