### PR TITLE
Fix pod security context

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- :wastebasket: Reverted commit: "Use jobs not plain pods for auxiliary tasks".
- :wastebasket: Removed openshift package and moved functionality elsewhere to avoid circular package dependencies.
- :bug: Fix pod security context -- set uid,git,fsgropu only on non-OpenShift.

### CODE REVIEW

**Comment by matejvasek** [comment]
PTAL @grafvonb

**Comment by grafvonb** [comment]
@matejvasek lgtm, it works as expected. The current version from `main` does not.

```
❯ ./func deploy --remote -v -p func-node-11-remote
Creating Pipeline resources
Running Pipeline Task: Building function image on the cluster
Running Pipeline Task: Deploying function to the cluster
✅ Function deployed in namespace "knative-func" and exposed at URL: 
   http://func-node-11-remote.knative-func.52.29.113.237.sslip.io
```

**Comment by matejvasek** [comment]
PTAL @jrangelramos @lance

**Review by lance — COMMENTED** [review]
/lgtm

**Comment by matejvasek** [comment]
@lance this requires test override.

**Pull request merged**
