### PR TITLE
corrected error msg

### LINKED ISSUE #2257: knative deployer failed to update the Knative Service:    referenced Secret xxxis not present
Hi,
I got this issue when re-reploying a service:

```bash
func deploy --remote
...
arning: git settings are only applicable when running with --remote.  Local source code will be used.deploy error: knative deployer failed to update the Knative Service: 
  referenced Secret "bing-apikey" is not present in namespace "agent-less"

Error: knative deployer failed to update the Knative Service: 
  referenced Secret "bing-apikey" is not present in namespace "agent-less"

```
However, the secret does exist in this namespace:

```
kn secret list -n agent-less
NAME                                        TYPE
bing-apikey                                 Opaque
```

I have a env using secret in the func.yaml:
```yaml
run:
  envs:
  - name: BING_API_KEY
    value: '{{ secret:bing-apikey:apiKey }}'
```

This issue only happens when re-reploying a function. The workaround is to delete the existing function first before deploy it:

```
func delete -n agent-less bing-search-tool
Removing Knative Service: bing-search-tool
Removing Knative Service 'bing-search-tool' and all dependent resources

func deploy --remote
```

### PR DESCRIPTION
**Pull request by swastik959**
# Changes

-
-
-

/kind bug

Fixes #2257

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by matejvasek** [comment]
@swastik959 you need to fix that linter error.

**Comment by swastik959** [comment]
@matejvasek should I remove the fmt.print for all the conditions ?

**Comment by matejvasek** [comment]
@swastik959 the `fmt.Sprint()` is unnecessary at line 969 since there is no formatting, you can use plain string there.

**Pull request merged**
