### PR TITLE
Fix PaC build

### PR DESCRIPTION
**Pull request by matejvasek**
```release-note
fix: pipelines as code build -- build via git hook in tekton
```

### CODE REVIEW

**Comment by matejvasek** [comment]
PTAL @lkingland @gauron99

**Comment by gauron99** [comment]
this should fix https://github.com/knative/func/issues/2185 right?

**Review by gauron99 — APPROVED** [review]
lgtm
/hold for others

**Comment by matejvasek** [comment]
PTAL @jrangelramos

**Pull request merged**
