### PR TITLE
Update springboot templates to Spring Boot 3.0.5

### PR DESCRIPTION
**Pull request by andrejusc**
# Changes

- Updated Spring Boot version from 3.0.2 to latest stable 3.0.5
- Updated Spring Cloud version from 2022.0.0 to latest stable 2022.0.2
- Made Maven compiler plugin to use latest version 3.11.0
- Made Maven surefire plugin (used for tests) to use latest version 3.0.0
- Updated Maven wrapper definition to utilize latest 3.9.1

/kind enhancement

Fixes #

**Release Note**

```release-note
Update springboot templates to Spring Boot 3.0.5
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by andrejusc** [comment]
@rhuss - I'm a newbie here in terms of PR. Could you help me to understand why Integration test is failing? I don't see anything obvious in produced output.

**Comment by matejvasek** [comment]
@andrejusc just some temporary error I guess, let me re-run tests.

**Comment by andrejusc** [comment]
@matejvasek - thank you, now re-run passed. So I think this could be merged then, could you do that?

**Comment by matejvasek** [comment]
/approve
/lgtm

@andrejusc Thanks for the contribution!

**Pull request merged**
