### PR TITLE
deps(node,typescript): update dependencies

### PR DESCRIPTION
**Pull request by lance**
Updates dependencies in Node.js and TypeScript functions to eliminate some security warnings and bump to faas-js-runtime 0.9.7, which allows for ESM modules now.

Signed-off-by: Lance Ball <lball@redhat.com>

/kind chore

```release-notes
Node.js and TypeScript functions now support ESM modules
```

### CODE REVIEW

**Comment by lance** [comment]
I don't know why the on-cluster tests are failing...

**Comment by matejvasek** [comment]
@lance some were probably flakes,
but typescript image start really fails:
```
docker run -it --rm -p8080:8080 quay.io/mvasek/fn-ts:latest
Environment: 
	DEV_MODE=false
	NODE_ENV=production
	DEBUG_PORT=5858
Launching via npm...
npm info using npm@8.15.0
npm info using node@v16.17.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:project Completed in 4ms
npm timing config:load:file:/opt/app-root/src/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/opt/app-root/src/.npm-global/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 3ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 14ms
npm timing npm:load:configload Completed in 14ms
npm timing npm:load:mkdirpcache Completed in 4ms
npm timing npm:load:mkdirplogs Completed in 1ms
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 8ms
npm timing npm:load:logFile Completed in 4ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 33ms

> event-handler@0.1.0 start
> FUNC_LOG_LEVEL=info faas-js-runtime ./build/index.js

⛔ Error: Cannot find module '/opt/app-root/src/build/package.json'
Require stack:
- /opt/app-root/src/node_modules/faas-js-runtime/lib/function-loader.js
- /opt/app-root/src/node_modules/faas-js-runtime/bin/cli.js
npm timing command:run Completed in 361ms
npm timing npm Completed in 402ms
npm info ok 

```

**Comment by matejvasek** [comment]
```
npm run start

> event-handler@0.1.0 start
> FUNC_LOG_LEVEL=info faas-js-runtime ./build/index.js

⛔ Error: Cannot find module '/tmp/tmp.5IKfYnlUuG/fn-ts/build/package.json'
Require stack:
- /tmp/tmp.5IKfYnlUuG/fn-ts/node_modules/faas-js-runtime/lib/function-loader.js
- /tmp/tmp.5IKfYnlUuG/fn-ts/node_modules/faas-js-runtime/bin/cli.js
```

**Comment by matejvasek** [comment]
cc @lholmquist

**Comment by matejvasek** [comment]
Does one need specific node version?

**Comment by lance** [comment]
@matejvasek thanks for looking into this. The problem is the ESM module loader that landed in this https://github.com/boson-project/faas-js-runtime/pull/140. It assumes there is a `package.json` file in the function directory, which, in the case of TypeScript functions will not be the case (it all ends up in `./build`). I'll open an issue on faas-js-runtime.

**Comment by lance** [comment]
/unhold
@matejvasek ptal
/cc @lkingland

**Review by lkingland — APPROVED** [review]
/lgtm

**Pull request merged**
