### PR TITLE
Rename knative-sandbox to knative-extensions

### PR DESCRIPTION
**Pull request by davidhadas**
This is an automated PR to replace knative-sandbox strings to knative-extensions.

### CODE REVIEW

**Comment by davidhadas** [comment]
@matejvasek  - this PR is suppose to be a simple string replacement of knative-sandbox to knative-extensions. 
It is created by an automated script. 
I am not sure why it make sense to add any other changes as part of this PR, please do such changes separately. 
If func is in some way a special case, please do the changes in a separate PR and we will delete this PR and create a new PR after such changes are done to replace all remaining strings.

**Comment by matejvasek** [comment]
> @matejvasek - this PR is suppose to be a simple string replacement of knative-sandbox to knative-extensions. It is created by an automated script. We gradually do that for all projects in both of knative orgs.
> 
> I am not sure why it make sense to add any other changes as part of this PR, please do such changes separately.
> 
> If func is in some way a special case, please do the changes in a separate PR and lets close this PR and create a new PR after such changes are done to replace all remaining strings.

My manual changes are required to make tests pass.

**Comment by davidhadas** [comment]
I assume we can close this PR as the needed change will be done manually

**Comment by kvmware** [comment]
This change is needed and can't be done manually without a review. Please link to new PR that incorporates this change.

**Comment by davidhadas** [comment]
will be done in a new PR as indicated earlier

**Comment by kvmware** [comment]
please leave this until you have a new PR so we can keep track

**Comment by lkingland** [comment]
Closing as superseded by #1905

**Pull request closed without merging**
