### PR TITLE
Update springboot template pom.xml dependencies

### PR DESCRIPTION
**Pull request by trisberg**
- update to use spring-cloud.version 2022.0.3
- remove springboot.platform.version property, not needed, rely on parent version
- remove import scope and pom type from spring-boot dependencies

# Changes

- :gift: update to use spring-cloud.version 2022.0.3
- :broom: remove springboot.platform.version property, not needed, rely on parent version
- :broom: remove import scope and pom type from spring-boot dependencies

/kind cleanup

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by matejvasek** [comment]
This need rebase because of conflict in `generate/zz_filesystem_generated.go`. Also the `generate/zz_filesystem_generated.go` file contains superfluous files like maven wrapper jars and vscode config files.

**Comment by matejvasek** [comment]
@ningyan325 PTAL

**Comment by trisberg** [comment]
Rebased and re-generated `generate/zz_filesystem_generated.go`

**Pull request merged**
