### PR TITLE
SSH tests

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

* tests for SSH connections

### CODE REVIEW

**Comment by matejvasek** [comment]
The `unit-tests_func_main` test is failing because it apparently runs under `root`.

**Comment by matejvasek** [comment]
PTAL @lkingland @gauron99 @jrangelramos

**Comment by matejvasek** [comment]
PTAL @lkingland @gauron99 @jrangelramos

**Comment by matejvasek** [comment]
@lance please override "On Cluster RT Test (1.20.2, ubuntu-latest, pack)" and "On Cluster RT Test (1.20.2, ubuntu-latest, s2i)"

**Comment by matejvasek** [comment]
PTAL @lkingland @gauron99 @jrangelramos

**Comment by matejvasek** [comment]
PTAL @lkingland @gauron99 @jrangelramos

**Review by lkingland — APPROVED** [review]

**Pull request merged**
