### PR TITLE
docs: add note about not supported on cluster build runtimes.

### PR DESCRIPTION
**Pull request by marcosnils**

### CODE REVIEW

**Comment by matejvasek** [comment]
Quarkus should work.

**Comment by marcosnils** [comment]
> Quarkus should work.

Just updated it.

**Comment by matejvasek** [comment]
/approve
/lgtm

Thanks @marcosnils !

**Review by matejvasek — APPROVED** [review]

**Review by zroubalik — APPROVED** [review]
/approve
/lgtm

Thanks for the contribution!

**Pull request merged**
