### PR TITLE
feat: deploy command global config with function context

### PR DESCRIPTION
**Pull request by lkingland**
- :gift: global config function context for the deploy command
- :gift: Enables build caching for deploy in more scenarios
- :gift: Adds tests for ENVs and attribute unsetting
- :broom: a wee bit of refactoring along the way

Related: #901 

/kind enhancement

**Release Note**

```release-note
Current function values more accurately reflected in 'deploy' command help text.
Builds cache more frequently when running func deploy
```

### CODE REVIEW

**Comment by lance** [comment]
Probably fixes: https://github.com/knative/func/issues/1492

**Comment by salaboy** [comment]
@lkingland it seems that this needs rebase, but it is looking good

**Review by salaboy — APPROVED** [review]
/lgtm

**Pull request merged**
