### PR TITLE
Propose lifecycle API hooks for Cloudevents SDK

### PR DESCRIPTION
**Pull request by matzew**
# Changes

- Propose lifecycle API hooks for Cloudevents SDK

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by matzew** [comment]
/hold
Let's discuss these hooks, but I think reusing the same APIs from the `http` version seems to be a good idea

**Comment by lkingland** [comment]
We'll want to update the instanced CloudEvent function's template in the same PR as the dependency is updated to include that functionality from `func-go`.  When it's tagged and released with a new version which includes the CloudEvents API additions, running `make update-runtimes` should pull it in

**Comment by matzew** [comment]
@lkingland the dependency is now in, and I rebased this

**Comment by matzew** [comment]
I do have sometimes bunch of new, untracked, files:

```
gst
On branch propose_lifecycle_hooks_CE
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   generate/zz_filesystem_generated.go
	modified:   third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/go.mod

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	pkg/functions/testdata/migrations/v0.19.0/.gitignore
	pkg/functions/testdata/migrations/v0.23.0-customized/.gitignore
	pkg/functions/testdata/migrations/v0.23.0/.gitignore
	pkg/functions/testdata/migrations/v0.25.0/.gitignore
	pkg/functions/testdata/migrations/v0.34.0/.gitignore
	pkg/functions/testdata/migrations/v0.35.0-nondefault/.gitignore
	pkg/functions/testdata/migrations/v0.35.0/.gitignore
	templates/go/.instanced-cloudevents/go.sum

```

**Pull request closed without merging**
