### PR TITLE
:broom: Removing the vendor dir :fireworks:

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :broom: Removing the vendor dir :fireworks:

/kind cleanup

Tests knative/hack#311
Tests knative/hack#222
Related to knative-extensions/kn-plugin-event#307

### CODE REVIEW

**Comment by cardil** [comment]
Error from https://github.com/knative/func/actions/runs/6108788480/job/16578494890?pr=1966#step:10:199 looks like infra related:

> `Error: preparing container for next step: creating build container: creating container: creating read-write layer with ID "75ac42ff146caa497d0a1b90a87bd6db05861249d055ee23e0557339b2161ec0": no space left on device`

**Comment by cardil** [comment]
https://github.com/knative/func/actions/runs/6108788480/job/16580443298#step:10:1 once again: `no space left on the device `

**Comment by cardil** [comment]
This PR is looking good (apart from obvious infra failures - seen above).

However, I'll put this on hold, since I'll be on PTO next week.

/hold

**Comment by lkingland** [comment]
/lgtm

Thanks for the improvement!  Re-running the E2E test...

**Comment by matejvasek** [comment]
@cardil to fix the failing test please rebase on `main`.

**Pull request merged**
