### PR TITLE
Update Rust templates dependencies and UTs for Actix 4.x

### PR DESCRIPTION
**Pull request by andrejusc**
# Changes

- Updated Rust dependencies to latest for Rust templates
- As Actix FW got updated to 4.3.1 - adjusted involved UTs
- Added primitive .gitignore to avoid `target/` from commit

/kind enhancement

Fixes #

**Release Note**

```release-note
Update Rust templates dependencies and UTs for Actix 4.x
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by andrejusc** [comment]
@dsimansk - how it looks for you?

**Comment by matejvasek** [comment]
@andrejusc  I think there are nightly builds https://storage.googleapis.com/knative-nightly/func/latest/func_linux_amd64

**Comment by andrejusc** [comment]
@matejvasek - what I meant to say - next 1.9.x release of this `func`, potentially 1.9.3 at the moment and then that to be picked up as `kn-func` plugin into overall `kn `tool. How is that flow handled?

**Comment by matejvasek** [comment]
> @matejvasek - what I meant to say - next 1.9.x release of this `func`, potentially 1.9.3 at the moment and then that to be picked up as `kn-func` plugin into overall `kn `tool. How is that flow handled?

/cc @lance

**Comment by lance** [comment]
@matejvasek @andrejusc I will create a cherry-pick PR for this on the 1.9 branch. That should cause 1.9.3 to land next Tuesday.

**Comment by andrejusc** [comment]
@lance - thank you for clarification. Please cherry-pick into 1.9 branch also another already merged PR #1658

**Pull request merged**
