### PR TITLE
chore: update faas-js-runtime to 0.10.0

### PR DESCRIPTION
**Pull request by lance**
Fixes: https://github.com/nodeshift/faas-js-runtime/issues/120

```release-note
Fixes an issue where Node.js and TypeScript functions are not killed immediately on SIGHUP
```

/kind chore

### CODE REVIEW

**Comment by lance** [comment]
> /approve /lgmt

@matejvasek can you fix the typo here? :)

**Comment by matejvasek** [comment]
@lance you either:
a) skip `Code Style / style / Lint`
b) put `package-lock.json` files to some linter ignore file.

**Comment by lance** [comment]
This is getting ridiculous
/override Code Style / style / Lint

**Pull request merged**
