### PR TITLE
fix: deploy annotations & labels correctly

### PR DESCRIPTION
**Pull request by zroubalik**
# Changes

- :broom: deploy annotations & labels correctly
- :broom: set timeout for integration test to 30mins

Fixes: https://github.com/knative/func/issues/1571

### CODE REVIEW

**Comment by lkingland** [comment]
I've noticed that my commands reliably fail when testing against a local cluster with the same messages seen here: "unable to get logs from container",  but only after a bit of a timeout.  This is appreciably affecting the time it takes to run the integration tests, and may be the reason it is going past the 10 minute limit.
Short fix would be to just increase the timeout of course

**Comment by zroubalik** [comment]
> I've noticed that my commands reliably fail when testing against a local cluster with the same messages seen here: "unable to get logs from container", but only after a bit of a timeout. This is appreciably affecting the time it takes to run the integration tests, and may be the reason it is going past the 10 minute limit. Short fix would be to just increase the timeout of course

@lkingland this make sense. What is the best place to set the timeout?

**Comment by lkingland** [comment]
> @lkingland this makes sense. What is the best place to set the timeout?

I think the go test command in the make target for integration requests.  See PMs :)

**Comment by zroubalik** [comment]
> > @lkingland this makes sense. What is the best place to set the timeout?
> 
> I think the go test command in the make target for integration requests. See PMs :)

Done that :)

**Pull request merged**
