### PR TITLE
fix: resolve tkn task spec locally

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- Remove Git task resolver and resolve the task specification locally. This is more reliable, git resolver is timing out on some clusters because git-clone is slow operation.

### CODE REVIEW

**Comment by matejvasek** [comment]
@lance PTAL

**Comment by matejvasek** [comment]
@jrangelramos please test this.

**Comment by jrangelramos** [comment]
I just tried.. and ot works properly! Thanks. it is much quicker than previous approach.

**Pull request merged**
