### PR TITLE
fix: push authorization validation for gcr.io

### LINKED ISSUE #1129: Func is no longer able to authenticate on `gcr.io` registry
I'm not able to use gcr.io as container registry. On previous version of func `v.0.24.0` I was able authenticate on google with using gcloud as below, and `func deploy` used to grab the saved credentials from `~/.docker/config.json` 

Currently, after authenticated, it requests for user/password and even entering the credentials (account + token) manually it can't authenticate

```
func deploy --path /tmp/func-node-http --registry gcr.io/sampleproject
...
Please provide credentials for image registry (gcr.io).
? Username: oauth2accesstoken
? Password: ***********************************************....
Incorrect credentials, please try again.

```

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- :bug: Fix push authorization validation for gcr.io

/kind bug

```release-note
fix: push authorization validation for gcr.io
```
resolves #1129

### CODE REVIEW

**Comment by matejvasek** [comment]
@jrangelramos try this out.

**Comment by jrangelramos** [comment]
it works fine with gcr.io, docker.io and quay.io

**Pull request merged**
