### PR TITLE
Remove axios dependency 

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- Removed dependency on `axios` by using `fetch()`.
- Fixed `getLatestPlatform()` by using the `tag_name` property instead of the `name` property.

### CODE REVIEW

**Comment by matejvasek** [comment]
@trisberg  Why the never Spring Boot works only with Java 17 not 21?

**Comment by trisberg** [comment]
> @trisberg Why the newer Spring Boot works only with Java 17 not 21?

It should work with Java 21, I use that all the time. What is the error and the failing config?

**Review by lkingland — APPROVED** [review]

**Comment by matejvasek** [comment]
PTAL @lkingland

**Comment by matejvasek** [comment]
I have idea why the coverage fails. @dsimansk @ReToCode please override it.

**Comment by matejvasek** [comment]
Why the **** is there `codecov/project` twice?

**Comment by matejvasek** [comment]
I just created completely new PR.

**Pull request closed without merging**
