### PR TITLE
fix: s2i python build on Windows

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- :bug: Fix s2i python build on Windows.

/kind bug

```release-note
fix: s2i python build on Windows
```

### CODE REVIEW

**Comment by matejvasek** [comment]
@jrangelramos does this work?

**Comment by matejvasek** [comment]
@lance please override the Lint.

**Comment by lance** [comment]
Overriding all of the style checks since this is basically a one-liner.

/override "style / suggester / shell"
/override "style / suggester / yaml"
/override "style / suggester / github_actions"

**Comment by matejvasek** [comment]
I have absolutely on idea why that one test is failing.
It is also failing on unrelated PR. Makes no sense.

**Comment by jrangelramos** [comment]
It seems to be related to this recent change https://github.com/knative/func/pull/1631/files#diff-12756d69e272b512547442b82be9dee485eff66dbce9705b46c164f2c814b00eL17 

I just tried a PR (using new previous actions) to confirm #1642

**Comment by lance** [comment]
> It seems to be related to this recent change https://github.com/knative/func/pull/1631/files#diff-12756d69e272b512547442b82be9dee485eff66dbce9705b46c164f2c814b00eL17
> 
> I just tried a PR (using new previous actions) to confirm #1642

Thanks for looking into this @jrangelramos - we should bubble this up to @knative/productivity-leads

**Comment by lance** [comment]
Even that is confusing though. Going back to the last SHA that had `go-test.yaml` in the repo, I don't see a real difference.

```
git co b28ad7ba3ca062ec9bdafa0f7b84cd4dca22a7a4
Previous HEAD position was c739e0b Drop unused matrix strategy and some step ids (#81)
HEAD is now at b28ad7b sync up changes for security workflow (#102)
```

```diff
diff go-test.yaml reusable-go-test.yaml
62c62
<         run: echo 'COVER_OPTS=-coverprofile=coverage.txt -covermode=atomic' >> $GITHUB_ENV
---
>         run: echo 'COVER_OPTS=-coverprofile=coverage.txt -covermode=atomic' >> "$GITHUB_ENV"
65c65
<         run: go test -race $COVER_OPTS ./...
---
>         run: go test -race "$COVER_OPTS ./..."
```

**Comment by matejvasek** [comment]
@lance please just override the test

**Pull request merged**
