### PR TITLE
[Release 1.9] cherry pick template updates for Rust and SpringBoot

### PR DESCRIPTION
**Pull request by lance**
Cherry pick https://github.com/knative/func/pull/1661 and https://github.com/knative/func/pull/1658 to the `release-1.9` branch.

```release-notes
Update Rust templates dependencies and UTs for Actix 4.x
Update springboot templates to Spring Boot 3.0.5
```

### CODE REVIEW

**Comment by matejvasek** [comment]
@andrejusc I am trying the templates but the produced images are not serving HTTP on 8080. Any idea what's wrong?

/hold

**Comment by matejvasek** [comment]
Hmm old templates do the same.

**Comment by matejvasek** [comment]
The HTTP works from within a container, but docker's `-p` forwarding is not working for me.

**Comment by matejvasek** [comment]
`curl: (56) Recv failure: Connection reset by peer`

**Comment by matejvasek** [comment]
I guess it's a bug in buildpacks.

/approve
/lgtm

**Comment by matejvasek** [comment]
The buildpacks are not exposing port on image for some reason.

/unhold

**Comment by andrejusc** [comment]
@lance - I thought there are some Rust image related build/test step inside those checks, but looking through them - only Rust Integration tests are there, but not image tests. I need to study how use case is done for Go case image inside checks (hopefully such is there) and then adopt for Rust, so we'll eliminate such potential breakage in future.
I'm not yet familiar deep enough with buildpacks to comment - will try to analyze more in upcoming days.

**Comment by andrejusc** [comment]
@lance - issue is with code line (which I didn't change) and this binding to listen:
https://github.com/knative/func/blob/main/templates/rust/http/src/main.rs#L28
`.bind(("127.0.0.1", port))?`
If such replace to this:
`.bind(("0.0.0.0", port))?`
it should potentially work.

Could you give it a try? Otherwise - I'll review more on weekend to correct.

**Comment by lance** [comment]
@andrejusc please work with @matejvasek on this next week. I will not be available until April 10.

**Pull request merged**
