### PR TITLE
chore: update CA bundle

### PR DESCRIPTION
**Pull request by matejvasek**
* Updated CA bundle 
* Added EoLs at EoFs
* Removed trailing whitespaces

### CODE REVIEW

**Comment by matejvasek** [comment]
PTAL @gauron99 @matzew @lkingland

**Comment by matejvasek** [comment]
Why linter started complaining on this PR?

**Comment by matejvasek** [comment]
PTAL @matzew @gauron99

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
