### PR TITLE
src: Use jobs not plain pods for auxiliary tasks

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- :broom: Use `job`s instead of plain `pod`s for auxiliary tasks.
  Rationale: `job` should have security context set properly automatically.

```release-note
use `job`s instead of plain `pod`s for auxiliary tasks
```

### CODE REVIEW

**Comment by matejvasek** [comment]
@grafvonb please review this and test it on AWS EKS. In particular try running on-cluster-build&re-build on EKS.

**Comment by grafvonb** [comment]
> @grafvonb please review this and test it on AWS EKS. In particular try running on-cluster-build&re-build on EKS.

I will look at this however during my current work on #1466 I get problems with the deploy task on EKS (Kubernetes v1.24). The error says that the `spec` for Knative Service is wrong. Do you now the issue?

```
❯ f deploy --remote -v
Creating Pipeline resources
Running Pipeline Task: Building function image on the cluster
Running Pipeline Task: Deploying function to the cluster
Error: failed to run pipeline: function pipeline run has failed with message:

⬆️  Deploying function to the cluster
W0712 07:45:15.552757      15 warnings.go:70] Kubernetes default value is insecure, Knative may default this to secure in a future release: spec.template.spec.containers[0].securityContext.allowPrivilegeEscalation, spec.template.spec.containers[0].securityContext.capabilities, spec.template.spec.containers[0].securityContext.runAsNonRoot, spec.template.spec.containers[0].securityContext.seccompProfile
Error: knative deployer failed to deploy the Knative Service: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: missing field(s): spec.template.spec.containers[0].image
deploy error: knative deployer failed to deploy the Knative Service: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: missing field(s): spec.template.spec.containers[0].image
```

**Comment by matejvasek** [comment]
> 

I don't know about the issue. Try asking in knative serving slack.

**Comment by matejvasek** [comment]
The `seccompProfile` warning is probably knative serving issue.
But the `missing field(s): spec.template.spec.containers[0].image` is really odd.

**Comment by grafvonb** [comment]
@matejvasek Due to the current workload at work, I will not be able to address this issue until the weekend. My plan is to set up a new cluster, since I can't do anything with the error mentioned above.

**Comment by grafvonb** [comment]
@matejvasek As discussed I have created today a new AWS EKS cluster with Kubernetes 1.27, latest Knative and Tekton to test this PR. The test was successful. Please find following logs with detailed information:

```
❯ k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3-eks-a5565ad

❯ k get nodes -o wide
NAME                                             STATUS   ROLES    AGE   VERSION               INTERNAL-IP     EXTERNAL-IP    OS-IMAGE         KERNEL-VERSION                  CONTAINER-RUNTIME
ip-172-31-29-159.eu-central-1.compute.internal   Ready    <none>   27h   v1.27.3-eks-a5565ad   172.31.29.159   3.66.18.102    Amazon Linux 2   5.10.184-175.731.amzn2.x86_64   containerd://1.6.19
ip-172-31-40-124.eu-central-1.compute.internal   Ready    <none>   27h   v1.27.3-eks-a5565ad   172.31.40.124   35.157.82.57   Amazon Linux 2   5.10.184-175.731.amzn2.x86_64   containerd://1.6.19
ip-172-31-9-54.eu-central-1.compute.internal     Ready    <none>   13m   v1.27.3-eks-a5565ad   172.31.9.54     3.79.4.254     Amazon Linux 2   5.10.184-175.731.amzn2.x86_64   containerd://1.6.19

❯ kn version
Version:      v1.10.0
Build Date:   2023-04-26T07:22:44Z
Git Revision: 46dbf661
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v1.10.0)
* Eventing
  - sources.knative.dev/v1 (knative-eventing v1.10.0)
  - eventing.knative.dev/v1 (knative-eventing v1.10.0)
  
 ❯ tkn version
Client version: 0.31.1
Pipeline version: v0.49.0

❯ g fetch origin pull/1857/head:PR-1857
❯ g switch PR-1857
❯ make build
❯ ./func version
v0.37.0-105-g0d386b95
❯ ./func create -l node func-node-1-remote-pr-1857
Created node function in /Users/adam/Development/Workspace/Knative/projects/func/func-node-1-remote-pr-1857
❯ ./func deploy -v --remote -p func-node-1-remote-pr-1857
Creating Pipeline resources
Running Pipeline Task: Building function image on the cluster
Running Pipeline Task: Deploying function to the cluster
✅ Function deployed in namespace "knative-func" and exposed at URL:
   http://func-node-1-remote-pr-1857.knative-func.3.121.145.23.sslip.io
```

It would be good to have this version released asap as the current version does not work:

```
❯ f version -v
Version: v0.37.0-6-gf38444bf
Knative: v1.10.0
Commit: f38444bf
SocatImage: quay.io/boson/alpine-socat:1.7.4.3-r1-non-root
TarImage: quay.io/boson/alpine-socat:1.7.4.3-r1-non-root
❯ f deploy -v --remote -p func-node-1-remote-pr-1857
Creating Pipeline resources
W0723 21:55:39.924577   27269 reflector.go:347] github.com/tektoncd/pipeline/pkg/client/informers/externalversions/factory.go:117: watch of *v1.PipelineRun ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"PipelineRun\" is registered for version \"tekton.dev/v1\" in scheme \"github.com/tektoncd/pipeline/pkg/client/clientset/versioned/scheme/register.go:32\"") has prevented the request from succeeding
...
```

**Comment by grafvonb** [comment]
> It would be good to have this version released asap as the current version does not work:
> 
See also https://github.com/knative/func/issues/1872

**Comment by matejvasek** [comment]
@grafvonb there should be release this week.

**Comment by matejvasek** [comment]
> > It would be good to have this version released asap as the current version does not work:
> 
> See also #1872

@grafvonb and it works all right on `main`, right?

**Comment by grafvonb** [comment]
> > > It would be good to have this version released asap as the current version does not work:
> > 
> > 
> > See also #1872
> 
> @grafvonb and it works all right on `main`, right?

Yeah, it works. To be 100% I've just built the current state of main:
```
❯ g log --oneline -1
8b46151b (HEAD -> main, origin/main, origin/HEAD) fix: resolve tkn task spec locally (#1885)
❯ ./func version -v
Version: v0.38.0-4-g8b46151b
Knative: v1.10.0
Commit: 8b46151b
SocatImage: quay.io/boson/alpine-socat:1.7.4.3-r1-non-root
TarImage: quay.io/boson/alpine-socat:1.7.4.3-r1-non-root
❯ ./func deploy -v --remote -p func-node-1-remote-main
Creating Pipeline resources
Running Pipeline Task: Building function image on the cluster
Running Pipeline Task: Deploying function to the cluster
✅ Function deployed in namespace "knative-func" and exposed at URL:
   http://func-node-1-remote-main.knative-func.3.121.145.23.sslip.io
```

**Review by lance — COMMENTED** [review]
/lgtm

**Pull request merged**
