### PR TITLE
Add support for `serviceAccountName` on deploy

### PR DESCRIPTION
**Pull request by saschagrunert**
# Changes

This allows setting the service account for the resulting knative service, which must pre-exist in the namespace to let the deployment succeed.

/kind feature

**Release Note**

```release-note
Added support for `serviceAccountName` in `func.yaml`'s deploy section to set the function service account.
```

**Docs**

```docs
None
```

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
Nice, could you please also update docs? https://github.com/knative/func/blob/main/docs/reference/func_yaml.md

**Comment by saschagrunert** [comment]
> Nice, could you please also update docs? https://github.com/knative/func/blob/main/docs/reference/func_yaml.md

Yep done :checkered_flag:

**Review by lance — COMMENTED** [review]
/lgtm

**Comment by lance** [comment]
@saschagrunert yes, I think this is a useful feature. It looks like someone else also wants it! https://github.com/knative/func/pull/1812

I think we should merge this PR and then @nitishchauhan0022 can rebase their PR which adds a flag for it to the `func deploy` command.

**Comment by matejvasek** [comment]
@saschagrunert isn't https://github.com/knative/func/pull/1812 superset of this PR?

**Comment by saschagrunert** [comment]
> @saschagrunert isn't #1812 superset of this PR?

Yes, probably. :)

**Pull request merged**
