### PR TITLE
adding service account support

### LINKED ISSUE #1439: Defining serviceaccount for the function
Currently, I have to edit the ksvc directly, so that the pod is able to access some of the k8s resources - there is no way to add serviceaccount through `func.yaml`.

### PR DESCRIPTION
**Pull request by nitishchauhan0022**
# Changes
Added the support for additon of service account from the func cli

Fixes #1439

### CODE REVIEW

**Comment by lance** [comment]
Hi @nitishchauhan0022 thanks for this! Can you please run `gofmt -s` and also update `docs/reference/func_yaml.md`? Thanks!

**Comment by nitishchauhan0022** [comment]
hey @lance I have formatted the output correctly and func_yaml.md will be rebased as you mentioned.

**Review by lkingland — APPROVED** [review]
Looks good to me

CC @jrangelramos would an E2E test be difficult for this one?

/hold for other 👀

**Comment by matejvasek** [comment]
@nitishchauhan0022 please rebase.

**Comment by matejvasek** [comment]
I did merge.

**Comment by nitishchauhan0022** [comment]
> > @nitishchauhan0022 please rebase.
> 
> I did merge main into this PR.

Thank you @matejvasek for doing this. I was away for couple of days.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
