### PR TITLE
migrate client-pkg to client/pkg

### PR DESCRIPTION
**Pull request by gauron99**

### CODE REVIEW

**Comment by matejvasek** [comment]
just a nit: I would not group `knative.dev/client` with `knative.dev/func`.

**Comment by gauron99** [comment]
Do you want to group it with github & k8s or should i put it separately?

**Comment by matejvasek** [comment]
> Do you want to group it with github & k8s or should i put it separately?

Yes group it with github.

I think that right now we do following grouping:
* Go stdlib
* external deps
* our own packages (knative.dev/func).

**Comment by cardil** [comment]
Looks good to me, but let maintainers approve.

**Pull request merged**
