### PR TITLE
Cleanup Rust cloudevents example

### PR DESCRIPTION
**Pull request by saschagrunert**
# Changes

- Using a more opinionated release profile to optimize binary
- Removing not required dependencies
- Updating the rest of the dependencies
- Switch to Rust edition 2021
- Cleanup imports by importing the concrete types
- Avoid unnecessary type assertions
- Do not unwrap port

/kind cleanup

**Release Note**

```release-note
Updated Rust cloudevents example.
```

**Docs**

```docs
None
```

### CODE REVIEW

**Comment by matejvasek** [comment]
When modifying templates the `generate/zz_filesystem_generated.go` file has to be updated too (`make generate/zz_filesystem_generated.go`).

**Comment by saschagrunert** [comment]
Thank you for the hint @matejvasek, updated the generated file.

**Comment by saschagrunert** [comment]
Rebased on top of main.

**Pull request merged**
