### PR TITLE
deps: update tekton to latest versions

### PR DESCRIPTION
**Pull request by lance**
# Changes

Fixes: https://github.com/knative/func/issues/1716

- :broom: Bumps `tekton/cli` and `tekton/pipelines` to 0.31.0 and 0.47.0 respectively.

/cc @jrangelramos

### CODE REVIEW

**Comment by matejvasek** [comment]
@lance this probably requires Go higher than 1.18.

**Comment by jrangelramos** [comment]
Hi @lance maybe we could upgrade CI scripts as well and see how it goes... https://github.com/knative/func/blob/main/hack/tekton.sh#L25

**Comment by jrangelramos** [comment]
btw it works fine with OSH Pipelines 1.10

**Comment by lance** [comment]
@knative/func-reviewers ptal

**Comment by matejvasek** [comment]
@lance you might need to override the linter

**Pull request merged**
