### PR TITLE
feat: specify create time for image built with buildpacks

### PR DESCRIPTION
**Pull request by cuichenli**
# Changes
Currently the image built with `func build` command all says the image was built 42 years ago. Although it was treated as a feature of buildpacks (in https://github.com/buildpacks/pack/issues/931#issuecomment-719524493), they have fixed this feature recently in https://github.com/buildpacks/imgutil/pull/138 hence I think it is worth to change the behavior here as well. 

/kind enhancement

Note: I am new to the func project and this change may be inappropriate, feel free to reject it. Thanks

### CODE REVIEW

**Comment by matejvasek** [comment]
I think we can have this but  I would prefer having this behind some config flag in `~/.config/func/config.yaml`.

**Comment by cuichenli** [comment]
yeah, definitely it would be great to make it configurable. if the owners are ok with this, i will try to implement it.

**Comment by matejvasek** [comment]
@lance @zroubalik wdyt?

**Comment by lance** [comment]
> @lance @zroubalik wdyt?

I agree behind a config flag would be nice

**Comment by lkingland** [comment]
Perhaps a Builder option `WithTimestamp(boolean)` which would be set when the builder is created in `cmd`, based on the value of a flag `--build-timestamp`?

**Comment by cuichenli** [comment]
i have updated accordingly, please let me know if i missed anything. thanks!

**Comment by matejvasek** [comment]
@cuichenli you need to fix one linter error.

**Comment by cuichenli** [comment]
i (think) i have fixed it in the latest commit, can you trigger the build again? thanks

**Review by lkingland — APPROVED** [review]
Looks really good. Thanks @cuichenli 

I re-ran the failed tests.  They've been flaky lately

**Pull request merged**
