### PR TITLE
Descriptions in JSON Schema

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- :gift: Add descriptions derived from doc comment in JSON Schema. The descriptions it then for instance displayed by IDEs when inspecting `func.yaml`.

/kind enhancement
/kind documentation

```release-note
feat: include description in JSON Schema 
```

### CODE REVIEW

**Comment by matejvasek** [comment]
@evankanderson any idea what failure of `Code Style / style / suggester / yaml` means? Why it is happening?

**Review by lance — APPROVED** [review]
A very nice improvement. Thanks 
/lgtm

**Review by lkingland — APPROVED** [review]
/lgtm
Very nice to have for IDEs 👍🏻

**Review by zroubalik — APPROVED** [review]
/lgtm

**Pull request merged**
