### PR TITLE
test: adding e2e test for func subscribe command

### PR DESCRIPTION
**Pull request by jrangelramos**
# Changes
- :gift: Adding e2e test for func subscribe 

/kind enhancement

### CODE REVIEW

**Comment by jrangelramos** [comment]
new test execution canbe found here https://github.com/knative/func/actions/runs/7466686343/job/20318596719?pr=2110#step:7:195

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matejvasek** [comment]
@ReToCode would you please override the "Integration Test (ubuntu-latest)" failure?

**Pull request merged**
