### PR TITLE
Usage of only proper handler API, no longer need for redundant Context

### PR DESCRIPTION
**Pull request by matzew**
# Changes

- :broom: Update temple doc, based on recent changes around their signature

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by lkingland — APPROVED** [review]

**Comment by ReToCode** [comment]
/override "On Cluster RT Test (ubuntu-latest, pack) (pull_request)"

**Comment by ReToCode** [comment]
/override "On Cluster RT Test (ubuntu-latest, pack) (pull_request)"

**Comment by ReToCode** [comment]
/override "On Cluster RT Test (ubuntu-latest, pack)"

**Comment by matejvasek** [comment]
@ReToCode we need to override also "E2E Test (rust) (pull_request)"

**Pull request merged**
