### PR TITLE
fix: ignore global config on docs gen

### PR DESCRIPTION
**Pull request by lkingland**
:bug: docs generator is affected by environment's global config

When adding the global config system, the docs generator needed to also be updated such that it does not encode the current environment's global settings in the generated docs (flag defaults).

### CODE REVIEW

**Comment by lkingland** [comment]
Is there a better way to do this?

**Comment by lance** [comment]
> Is there a better way to do this?

Seems reasonable to me.

**Review by lance — COMMENTED** [review]
/lgtm

**Comment by lance** [comment]
/override "On Cluster RT Test (1.18.x, ubuntu-latest)"

**Pull request merged**
