### PR TITLE
Continue on error when one of runtimes fails

### PR DESCRIPTION
**Pull request by matejvasek**

### CODE REVIEW

**Comment by matejvasek** [comment]
@lance please override "On Cluster RT Test (1.20.2, ubuntu-latest, pack)" and "On Cluster RT Test (1.20.2, ubuntu-latest, s2i)"

**Comment by lance** [comment]
/override "On Cluster RT Test (1.20.2, ubuntu-latest, s2i)"

**Comment by matejvasek** [comment]
PTAL @jrangelramos @gauron99 @lkingland

**Pull request merged**
